repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://github.com/realityforge/repository/raw/master/

artifacts:
  asm: org.ow2.asm:asm-all:jar:5.0.2
  jdom: org.jdom:jdom:jar:1.1
